/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    CommonMenu: typeof import('./src/components/FooterComponents/CommonMenu.vue')['default']
    DesktopMenu: typeof import('./src/components/FooterComponents/DesktopMenu.vue')['default']
    LeaderBoardsTops: typeof import('./src/components/LeaderBoardsTops.vue')['default']
    LoginWithSteam: typeof import('./src/components/LoginWithSteam.vue')['default']
    MobilePhoneMenu: typeof import('./src/components/FooterComponents/MobilePhoneMenu.vue')['default']
    PageTitle: typeof import('./src/components/PageCommon/PageTitle.vue')['default']
    ParallaxDesktop: typeof import('./src/components/UserInfomation/ParallaxDesktop.vue')['default']
    ParallaxMobile: typeof import('./src/components/UserInfomation/ParallaxMobile.vue')['default']
    ProfileEditButton: typeof import('./src/components/UserInfomation/ProfileEditButton.vue')['default']
    RecordsListTableS1: typeof import('./src/components/RecordsComponents/RecordsListTableS1.vue')['default']
    RecordsListTableS2: typeof import('./src/components/RecordsComponents/RecordsListTableS2.vue')['default']
    RecordsListTableT: typeof import('./src/components/RecordsComponents/RecordsListTableT.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RunInfoBodyS: typeof import('./src/components/RunInfoComponents/RunInfoBodyS.vue')['default']
    RunInfoBodyT: typeof import('./src/components/RunInfoComponents/RunInfoBodyT.vue')['default']
    RunInfoCard: typeof import('./src/components/RunInfoCard.vue')['default']
    RunInfoHeadImg: typeof import('./src/components/RunInfoComponents/RunInfoHeadImg.vue')['default']
    RunInfoHeadImgS: typeof import('./src/components/RunInfoComponents/RunInfoHeadImgS.vue')['default']
    SourceJumpUser: typeof import('./src/components/UserInfomation/SourceJumpUser.vue')['default']
    TeasBHOPUser: typeof import('./src/components/UserInfomation/TeasBHOPUser.vue')['default']
    TranslateButton: typeof import('./src/components/TranslateButton.vue')['default']
  }
}
